version: '{build}'
configuration: Release
image: Visual Studio 2019 Preview

install:
- ps: |-
    choco install dotnetcore-sdk --version 3.0.100

cache:
- C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\vcredist140 -> .appveyor.yml
- C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\dotnetcore-sdk -> .appveyor.yml

environment:
  NpmAuthToken:
    secure: ZdHER7r/cd8BLWjrL4OUjksloJt2CaGHXdWvS9dsPCaKxHpO1FLyQJjzqfPVzBmE

before_build:
- dotnet restore

build_script:
- dotnet build --configuration Release

test_script:
- mirrorsharp test
  
after_test:
- mirrorsharp pack

artifacts:
- path: '*.nupkg'
- path: '*.tgz'

deploy:
  - provider: NuGet
    on:
      branch: /^(master|\d\.\d)$/
    api_key:
      secure: rV20COJkB2Lt/O6E7NvcdMJlHtBS8C7uuUWhFXu6XTPmEVqAeMKCDyz/yuOZwVRo
    artifact: /.*\.nupkg/

after_deploy:
- ps: .\Publish-ToNpm.ps1