version: '{build}'
configuration: Release

environment:
  "npm_config_//registry.npmjs.org/:_authToken":
    secure: Y7AyDXAcvBiXCfBEX8LMNg8WI8/mvse0ULxs1Ip3/yFxr8m4PqPG1H2D2ZWJFoaJ

before_build:
- dotnet restore

build:
  verbosity: minimal

test_script:
- dotnet test MirrorSharp.Tests
  
after_test:
- .\pack-all.bat

artifacts:
- path: '*.nupkg'
- path: '*.tgz'

deploy:
  - provider: NuGet
    on:
      branch: master
    api_key:
      secure: rV20COJkB2Lt/O6E7NvcdMJlHtBS8C7uuUWhFXu6XTPmEVqAeMKCDyz/yuOZwVRo
    artifact: /.*\.nupkg/

after_deploy:
- ps: Get-Item *.tgz | % { npm publish $($_.FullName) }