version: '{build}'
configuration: Release

environment:
  NpmAuthToken:
    secure: Y7AyDXAcvBiXCfBEX8LMNg8WI8/mvse0ULxs1Ip3/yFxr8m4PqPG1H2D2ZWJFoaJ

before_build:
- dotnet restore

build_script:
- dotnet build --configuration Release

test_script:
- dotnet test Tests.Roslyn2\Tests.Roslyn2.csproj
# https://github.com/ashmind/mirrorsharp/issues/65
#- dotnet test Tests.Roslyn2.Net46\Tests.Roslyn2.Net46.csproj
  
after_test:
- .\pack-all.bat

artifacts:
- path: '*.nupkg'
- path: '*.tgz'

deploy:
  - provider: NuGet
    on:
      branch: /^(master|\d\.\d)$/
    api_key:
      secure: rV20COJkB2Lt/O6E7NvcdMJlHtBS8C7uuUWhFXu6XTPmEVqAeMKCDyz/yuOZwVRo
    artifact: /.*\.nupkg/

after_deploy:
- ps: .\Publish-ToNpm.ps1