version: '{build}'
configuration: Release
image: Visual Studio 2019

environment:
  NpmAuthToken:
    secure: ZdHER7r/cd8BLWjrL4OUjksloJt2CaGHXdWvS9dsPCaKxHpO1FLyQJjzqfPVzBmE

install:
- ps: |-
    Install-Product node 13.2.0

before_build:
- ms restore

build_script:
- ms build Release

test_script:
- ms test

after_test:
- ms pack Release

artifacts:
- path: '*.nupkg'
- path: '*.tgz'

deploy:
  - provider: NuGet
    on:
      branch: /^(master|\d\.\d|feature\/codemirror-6)$/
    api_key:
      secure: rV20COJkB2Lt/O6E7NvcdMJlHtBS8C7uuUWhFXu6XTPmEVqAeMKCDyz/yuOZwVRo
    artifact: /.*\.nupkg/

after_deploy:
- ps: .\Publish-ToNpm.ps1